insert into categories (name)
values ('American'),
       ('Italian'),
       ('Mexican'),
       ('Polish'),
       ('Chinese'),
       ('Japanese'),
       ('Indian'),
       ('French'),
       ('Thai'),
       ('Spanish'),
       ('Greek'),
       ('Korean'),
       ('Vietnamese'),
       ('Turkish'),
       ('Brazilian'),
       ('Lebanese'),
       ('Ethiopian'),
       ('Moroccan'),
       ('German'),
       ('Russian'),
       ('Caribbean');